### ISSUE TITLE
Enable Fortan Ada, optionally 

### ISSUE THREAD

**Issue by 3246251196** [AmigaLabs/adtools#11]
@kas1e says that Fortran works. So does ADA.

Test this out - check it also builds with 'native-install' makefile target. Enable an option in the Makefile to build these. We probably do not want to do this by default if it increases the build time too much.

**Comment by kas1e** [comment]
@3246251196 Enabling Fortran surely increase compiling speed a lot (when i tried in the past, it take pretty much more time).
Also almost no one use Fortran or ADA on OS4 for any real programming , so it all mostly matter of funny check. But maybe worth to note in some main readme , that if you need Fortran you can enable by just providing `fortran` to ```--enable-languages``` in configure. 

I also tried objc and obj-c++ - they also compiles fine in (which i do not remember if we have enabled by default?). Maybe also worth note that it can be inbuild in.

From another side, for things like Dockers or ready images, etc, where time of compilation of the whole adtools make no differences for end users, it can be build with everything, imho. But .. we just can't support it all in the way we all support C and C++ due limited resources and interest, imho.

**Comment by 3246251196** [comment]
@walkero-gr 
Do you know if we _need_ ObjC for webkit, or can we get away without it?

**Comment by walkero-gr** [comment]
> @walkero-gr Do you know if we _need_ ObjC for webkit, or can we get away without it?

No, we do not need Obj-C for the webkit. Webkit already compiles just fine.
