### ISSUE TITLE
Update the SPEC file for new-age options

### ISSUE THREAD

**Issue by 3246251196** [AmigaLabs/adtools#5]
@afxgroup 
We should discus this on the 26th October. e.g. machine target command line options that are out of date in the SPEC file.

**Comment by 3246251196** [comment]
Bump. For the next meeting after the 7th.

**Comment by afxgroup** [comment]
Yes, we'll arrange a meeting

**Comment by afxgroup** [comment]
Rebump! I need it :P

**Comment by 3246251196** [comment]
@afxgroup 
Can you quote what the changes or the bulk of new options are?

**Comment by afxgroup** [comment]
If you try to compile something that has specific cpu code it doesn't work anymore with gcc11 (and iirc 8)
For example:
http://www.os4depot.net/?function=showfile&file=utility/shell/sam440ep_setup.lha

But also code with altivec. A good test is also the graphics library

**Comment by 3246251196** [comment]
@afxgroup 
Reminder to prove the spec file in this issue when you have the time.

**Comment by 3246251196** [comment]
@afxgroup 
https://github.com/AmigaLabs/adtools/tree/gcc11_spec_machine_options
Perhaps we can test this out a little bit on some projects that you know fail. I happened to test it for the sam440 LHA above and it worked.

===
I was wondering why this actually fixed anything since the 440fp option has not changed in this new spec file. For sure, we should update our spec file and I will create the PR, but the real fix is the implicit inclusion of this option:
``` 
-many
    Generate code for any architecture (PWR/PWRX/PPC).
```
due to the last entry for ASM_CPU_SPEC which is ASM_OPT_ANY.
Well, that at least is the fix for the test file that you provided in the ticket. I am sure updating our spec file also fixes other more intricate things!

**Comment by 3246251196** [comment]
@3246251196 
TODO: See https://github.com/sba1/adtools/pull/164. Merge this into our Master instead.

**Comment by 3246251196** [comment]
Since we agreed to start using our own AmigaLabs fork from now on and this is merged. This issue is now closed and resolved.
