### ISSUE TITLE
Fix -pthread switch

### ISSUE THREAD

**Issue by afxgroup** [AmigaLabs/adtools#9]
Latest gcc version has a problem with `-pthread` switch. we need to add it back using:

```
#undef LIB_SPEC
#define LIB_SPEC "\
--start-group %{pthread:-lpthread} -lc --end-group"
```

**Comment by 3246251196** [comment]
Can you check https://github.com/AmigaLabs/adtools/tree/allow_pthread_option_ld_phase_only

**Comment by 3246251196** [comment]
Also merged to mainline.
